spring.application.name=pet-shop
server.port=8080

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=${PET_SHOP_DB_URL}
spring.datasource.username=${PET_SHOP_DB_USERNAME}
spring.datasource.password=${PET_SHOP_DB_PASSWORD}

spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8

mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.global-config.banner=false
